// <auto-generated />
using System;
using CulinaryMap.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CulinaryMap.Migrations
{
    [DbContext(typeof(CulinaryMapDbContext))]
    [Migration("20230412120225_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CulinaryMap.Entities.IngredientDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Kcal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IngredientDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kcal = 0,
                            Name = "Fasole alba boabe"
                        },
                        new
                        {
                            Id = 2,
                            Kcal = 0,
                            Name = "Morcov"
                        },
                        new
                        {
                            Id = 3,
                            Kcal = 0,
                            Name = "Pastarnac"
                        },
                        new
                        {
                            Id = 4,
                            Kcal = 0,
                            Name = "Ciolan Afumat"
                        },
                        new
                        {
                            Id = 5,
                            Kcal = 0,
                            Name = "Carnat Afumat"
                        },
                        new
                        {
                            Id = 6,
                            Kcal = 0,
                            Name = "Costita Afumata"
                        },
                        new
                        {
                            Id = 7,
                            Kcal = 0,
                            Name = "Foaie Dafin"
                        },
                        new
                        {
                            Id = 8,
                            Kcal = 0,
                            Name = "Ceapa alba"
                        },
                        new
                        {
                            Id = 9,
                            Kcal = 0,
                            Name = "Faina"
                        },
                        new
                        {
                            Id = 10,
                            Kcal = 0,
                            Name = "Suc de rosii"
                        },
                        new
                        {
                            Id = 11,
                            Kcal = 0,
                            Name = "Tarhon"
                        },
                        new
                        {
                            Id = 12,
                            Kcal = 0,
                            Name = "Otet"
                        },
                        new
                        {
                            Id = 13,
                            Kcal = 0,
                            Name = "Lapte cald"
                        },
                        new
                        {
                            Id = 14,
                            Kcal = 0,
                            Name = "Galbenus"
                        },
                        new
                        {
                            Id = 15,
                            Kcal = 0,
                            Name = "Smantana de gatit"
                        },
                        new
                        {
                            Id = 16,
                            Kcal = 0,
                            Name = "Ulei"
                        },
                        new
                        {
                            Id = 17,
                            Kcal = 0,
                            Name = "Sare"
                        },
                        new
                        {
                            Id = 18,
                            Kcal = 0,
                            Name = "Piper"
                        },
                        new
                        {
                            Id = 19,
                            Kcal = 0,
                            Name = "Boia de ardei dulce"
                        },
                        new
                        {
                            Id = 20,
                            Kcal = 0,
                            Name = "Boia de ardei iute"
                        },
                        new
                        {
                            Id = 21,
                            Kcal = 0,
                            Name = "Patrunjel"
                        },
                        new
                        {
                            Id = 22,
                            Kcal = 0,
                            Name = "Telina"
                        },
                        new
                        {
                            Id = 23,
                            Kcal = 0,
                            Name = "Ceapa verde"
                        },
                        new
                        {
                            Id = 24,
                            Kcal = 0,
                            Name = "Usturoi"
                        },
                        new
                        {
                            Id = 25,
                            Kcal = 0,
                            Name = "Orez"
                        },
                        new
                        {
                            Id = 26,
                            Kcal = 0,
                            Name = "Mazare"
                        },
                        new
                        {
                            Id = 27,
                            Kcal = 0,
                            Name = "Ou"
                        },
                        new
                        {
                            Id = 28,
                            Kcal = 0,
                            Name = "Supa de legume"
                        },
                        new
                        {
                            Id = 29,
                            Kcal = 0,
                            Name = "Apa"
                        },
                        new
                        {
                            Id = 30,
                            Kcal = 0,
                            Name = "Carne tocata porc"
                        },
                        new
                        {
                            Id = 31,
                            Kcal = 0,
                            Name = "Varza Murata"
                        },
                        new
                        {
                            Id = 32,
                            Kcal = 0,
                            Name = "Ulei de masline"
                        },
                        new
                        {
                            Id = 33,
                            Kcal = 0,
                            Name = "Smantana"
                        },
                        new
                        {
                            Id = 34,
                            Kcal = 0,
                            Name = "Cimbru"
                        },
                        new
                        {
                            Id = 35,
                            Kcal = 0,
                            Name = "Rosii"
                        },
                        new
                        {
                            Id = 36,
                            Kcal = 0,
                            Name = "Drojdie Proaspata"
                        },
                        new
                        {
                            Id = 37,
                            Kcal = 0,
                            Name = "Drojdie Uscata"
                        },
                        new
                        {
                            Id = 38,
                            Kcal = 0,
                            Name = "Zahar"
                        },
                        new
                        {
                            Id = 39,
                            Kcal = 0,
                            Name = "Zahar Vanilat"
                        },
                        new
                        {
                            Id = 40,
                            Kcal = 0,
                            Name = "Branza Sarata"
                        },
                        new
                        {
                            Id = 41,
                            Kcal = 0,
                            Name = "Branza de vaci"
                        },
                        new
                        {
                            Id = 42,
                            Kcal = 0,
                            Name = "Branza de oaie"
                        },
                        new
                        {
                            Id = 43,
                            Kcal = 0,
                            Name = "Branza Telemea"
                        },
                        new
                        {
                            Id = 44,
                            Kcal = 0,
                            Name = "Burta de vita"
                        },
                        new
                        {
                            Id = 45,
                            Kcal = 0,
                            Name = "Ardei gras"
                        },
                        new
                        {
                            Id = 46,
                            Kcal = 0,
                            Name = "Esenta de rom"
                        },
                        new
                        {
                            Id = 47,
                            Kcal = 0,
                            Name = "Esenta de vanilie"
                        },
                        new
                        {
                            Id = 48,
                            Kcal = 0,
                            Name = "Cacao"
                        },
                        new
                        {
                            Id = 49,
                            Kcal = 0,
                            Name = "Nuca"
                        },
                        new
                        {
                            Id = 50,
                            Kcal = 0,
                            Name = "Coaja de lamaie"
                        },
                        new
                        {
                            Id = 51,
                            Kcal = 0,
                            Name = "Coaja de portocala"
                        },
                        new
                        {
                            Id = 52,
                            Kcal = 0,
                            Name = "Cartof"
                        },
                        new
                        {
                            Id = 53,
                            Kcal = 0,
                            Name = "Rasol de vitel"
                        },
                        new
                        {
                            Id = 54,
                            Kcal = 0,
                            Name = "Fasole verde"
                        },
                        new
                        {
                            Id = 55,
                            Kcal = 0,
                            Name = "Bors"
                        },
                        new
                        {
                            Id = 56,
                            Kcal = 0,
                            Name = "Fasole Rosie Boabe"
                        },
                        new
                        {
                            Id = 57,
                            Kcal = 0,
                            Name = "Marar"
                        },
                        new
                        {
                            Id = 58,
                            Kcal = 0,
                            Name = "Praz"
                        },
                        new
                        {
                            Id = 59,
                            Kcal = 0,
                            Name = "Slanina"
                        },
                        new
                        {
                            Id = 60,
                            Kcal = 0,
                            Name = "Gris"
                        },
                        new
                        {
                            Id = 61,
                            Kcal = 0,
                            Name = "Carne de miel"
                        },
                        new
                        {
                            Id = 62,
                            Kcal = 0,
                            Name = "Clatite"
                        },
                        new
                        {
                            Id = 63,
                            Kcal = 0,
                            Name = "Unt"
                        },
                        new
                        {
                            Id = 64,
                            Kcal = 0,
                            Name = "Stafide"
                        },
                        new
                        {
                            Id = 65,
                            Kcal = 0,
                            Name = "Albus"
                        },
                        new
                        {
                            Id = 66,
                            Kcal = 0,
                            Name = "Ceapa rosie"
                        },
                        new
                        {
                            Id = 67,
                            Kcal = 0,
                            Name = "Carnat iute"
                        },
                        new
                        {
                            Id = 68,
                            Kcal = 0,
                            Name = "Masline"
                        },
                        new
                        {
                            Id = 69,
                            Kcal = 0,
                            Name = "Vin Rosu"
                        },
                        new
                        {
                            Id = 70,
                            Kcal = 0,
                            Name = "Bulion"
                        },
                        new
                        {
                            Id = 71,
                            Kcal = 0,
                            Name = "Vin Alb"
                        },
                        new
                        {
                            Id = 72,
                            Kcal = 0,
                            Name = "Paine inmuiata in lapte"
                        },
                        new
                        {
                            Id = 73,
                            Kcal = 0,
                            Name = "Pesmet"
                        },
                        new
                        {
                            Id = 74,
                            Kcal = 0,
                            Name = "Prune"
                        },
                        new
                        {
                            Id = 75,
                            Kcal = 0,
                            Name = "Pui"
                        },
                        new
                        {
                            Id = 76,
                            Kcal = 0,
                            Name = "Radacina de patrunjel"
                        },
                        new
                        {
                            Id = 77,
                            Kcal = 0,
                            Name = "Boabe de piper"
                        },
                        new
                        {
                            Id = 78,
                            Kcal = 0,
                            Name = "Gulie"
                        },
                        new
                        {
                            Id = 79,
                            Kcal = 0,
                            Name = "Conopida"
                        },
                        new
                        {
                            Id = 80,
                            Kcal = 0,
                            Name = "Dovlecel"
                        },
                        new
                        {
                            Id = 81,
                            Kcal = 0,
                            Name = "Miere"
                        },
                        new
                        {
                            Id = 82,
                            Kcal = 0,
                            Name = "Scortisoara"
                        },
                        new
                        {
                            Id = 83,
                            Kcal = 0,
                            Name = "Malai"
                        },
                        new
                        {
                            Id = 84,
                            Kcal = 0,
                            Name = "Cas"
                        },
                        new
                        {
                            Id = 85,
                            Kcal = 0,
                            Name = "Paine"
                        },
                        new
                        {
                            Id = 86,
                            Kcal = 0,
                            Name = "Carne tocata vita"
                        },
                        new
                        {
                            Id = 87,
                            Kcal = 0,
                            Name = "Cap de porc"
                        },
                        new
                        {
                            Id = 88,
                            Kcal = 0,
                            Name = "Picioare de porc"
                        },
                        new
                        {
                            Id = 89,
                            Kcal = 0,
                            Name = "Carne de porc"
                        },
                        new
                        {
                            Id = 90,
                            Kcal = 0,
                            Name = "Iaurt"
                        },
                        new
                        {
                            Id = 91,
                            Kcal = 0,
                            Name = "Urda"
                        },
                        new
                        {
                            Id = 92,
                            Kcal = 0,
                            Name = "Apa Carbogazificata"
                        },
                        new
                        {
                            Id = 93,
                            Kcal = 0,
                            Name = "Ciuperci"
                        },
                        new
                        {
                            Id = 94,
                            Kcal = 0,
                            Name = "Leurda"
                        },
                        new
                        {
                            Id = 95,
                            Kcal = 0,
                            Name = "Jumari"
                        },
                        new
                        {
                            Id = 96,
                            Kcal = 0,
                            Name = "Magiun"
                        },
                        new
                        {
                            Id = 97,
                            Kcal = 0,
                            Name = "Nucsoara"
                        },
                        new
                        {
                            Id = 98,
                            Kcal = 0,
                            Name = "Caltabos Afumat"
                        },
                        new
                        {
                            Id = 99,
                            Kcal = 0,
                            Name = "Ardei iute"
                        },
                        new
                        {
                            Id = 100,
                            Kcal = 0,
                            Name = "Peste (la alegere)"
                        },
                        new
                        {
                            Id = 101,
                            Kcal = 0,
                            Name = "Medalion Crap"
                        },
                        new
                        {
                            Id = 102,
                            Kcal = 0,
                            Name = "Macrou"
                        },
                        new
                        {
                            Id = 103,
                            Kcal = 0,
                            Name = "Porumb"
                        },
                        new
                        {
                            Id = 104,
                            Kcal = 0,
                            Name = "Cascaval"
                        },
                        new
                        {
                            Id = 105,
                            Kcal = 0,
                            Name = "Chimen"
                        });
                });

            modelBuilder.Entity("CulinaryMap.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Latitude")
                        .HasColumnType("int");

                    b.Property<int>("Longitude")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CulinaryMap.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId")
                        .IsUnique();

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("CulinaryMap.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CulinaryHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CulinaryHistory = "In Transilvania, Banat si Crisana, influenta germana se face simtita prin varietatea de carnati si mezeluri, cum ar fi virsli sau casul de cap de porc, dar și în consumul de ciorbe groase și varza. Branza de burduf este una dintre specialitatile acestei regiuni, la fel ca si casul de Nasal, o alta branza, maturata intr-o pestera din Taga, Cluj. Influentele bucatariilor maghiare si sarbe sunt si ele simtite prin prezenta cozonacului secuiesc, gulasului sau a multor bauturi tari precum palinca, horinca si slibovita.",
                            Name = "Transilvania"
                        },
                        new
                        {
                            Id = 2,
                            CulinaryHistory = "In Transilvania, Banat si Crisana, influenta germana se face simtita prin varietatea de carnati si mezeluri, cum ar fi virsli sau casul de cap de porc, dar și în consumul de ciorbe groase și varza. Branza de burduf este una dintre specialitatile acestei regiuni, la fel ca si casul de Nasal, o alta branza, maturata intr-o pestera din Taga, Cluj. Influentele bucatariilor maghiare si sarbe sunt si ele simtite prin prezenta cozonacului secuiesc, gulasului sau a multor bauturi tari precum palinca, horinca si slibovita.",
                            Name = "Banat"
                        },
                        new
                        {
                            Id = 3,
                            CulinaryHistory = "In Transilvania, Banat si Crisana, influenta germana se face simtita prin varietatea de carnati si mezeluri, cum ar fi virsli sau casul de cap de porc, dar și în consumul de ciorbe groase și varza. Branza de burduf este una dintre specialitatile acestei regiuni, la fel ca si casul de Nasal, o alta branza, maturata intr-o pestera din Taga, Cluj. Influentele bucatariilor maghiare si sarbe sunt si ele simtite prin prezenta cozonacului secuiesc, gulasului sau a multor bauturi tari precum palinca, horinca si slibovita.",
                            Name = "Crisana"
                        },
                        new
                        {
                            Id = 4,
                            CulinaryHistory = "Oltenia si Muntenia sunt cele doua provincii care au format in trecut Tara Romaneasca, vecina cu Bulgaria, Transilvania și Dobrogea. Cele doua regiuni au o lunga istorie de productie a vinului, cu trei regiuni mari viticole impartite in 13 mari podgorii. Din aceste regiuni provin mancaruri precum ostropelul, ciorba de burta, tuslamaua si ciorba de potroace. Oltenia este renumita pentru carnatii sai. Din Muntenia provin covrigii din Buzau, babicul, carnații de Plescoi, magiunul de Topoloveni si Salamul de Sibiu (originar, de fapt, din Sinaia).",
                            Name = "Muntenia"
                        },
                        new
                        {
                            Id = 5,
                            CulinaryHistory = "Oltenia si Muntenia sunt cele doua provincii care au format in trecut Tara Romaneasca, vecina cu Bulgaria, Transilvania și Dobrogea. Cele doua regiuni au o lunga istorie de productie a vinului, cu trei regiuni mari viticole impartite in 13 mari podgorii. Din aceste regiuni provin mancaruri precum ostropelul, ciorba de burta, tuslamaua si ciorba de potroace. Oltenia este renumita pentru carnatii sai. Din Muntenia provin covrigii din Buzau, babicul, carnații de Plescoi, magiunul de Topoloveni si Salamul de Sibiu (originar, de fapt, din Sinaia).",
                            Name = "Oltenia"
                        },
                        new
                        {
                            Id = 6,
                            CulinaryHistory = "Diversitatea etnica a Dobrogei ofera regiunii un caracter diferit de Muntenia vecina, bucataria regionala incorporand elementele aduse de turcii, tatarii, grecii, aromanii si lipovenii din regiune. Din judetul Tulcea unde se afla Delta Dunarii, bogata in specii de pesti, provin specialitati precum borșul de pește lipovenesc, storceagul sau saramura de sturion. În județul Constanța se produce vinul Murfatlar din Regiunea Viticolă a Colinelor Dobrogei. Datorită influenței orientale, sunt comune deserturile precum baclavaua, halvaua și sarailiile, mâncăruri precum șuberecul umplut cu carne prăjită cu ceapă, și mezeluri precum ghiudemul și sugiucul. Dobrogea a fost istoric străbătută de păstori, produsele din carne de oaie fiind comune, mai ales în rețetele împrumutate din bucătăriile orientale sau din bucătăria aromână, cât și în rețete autohtone, precum cea de pastramă.",
                            Name = "Dobrogea"
                        },
                        new
                        {
                            Id = 7,
                            CulinaryHistory = "Moldova occidentală, Bucovina, Republica Moldova și Bugeacul au format cândva Moldova istorică, a cărei bucătării a fost influențată de cea poloneză, austriacă, rusă și ucraineană. Bucătăria moldovenească este un amestec de arome acide și texturi cremoase, cu o mai abundentă utilizare a verzei, a cartofilor și a cepei. Printre specialitățile locale se numără ciulamaua și tochitura moldovenească. În aceste regiuni, sarmalele se prepară și cu frunze de viță de vie. Pârjoalele moldovenești sunt chifteluțe tocate la grătar, cu usturoi și ierburi aromatice.",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 8,
                            CulinaryHistory = "Moldova occidentală, Bucovina, Republica Moldova și Bugeacul au format cândva Moldova istorică, a cărei bucătării a fost influențată de cea poloneză, austriacă, rusă și ucraineană. Bucătăria moldovenească este un amestec de arome acide și texturi cremoase, cu o mai abundentă utilizare a verzei, a cartofilor și a cepei. Printre specialitățile locale se numără ciulamaua și tochitura moldovenească. În aceste regiuni, sarmalele se prepară și cu frunze de viță de vie. Pârjoalele moldovenești sunt chifteluțe tocate la grătar, cu usturoi și ierburi aromatice.",
                            Name = "Bucovina"
                        },
                        new
                        {
                            Id = 9,
                            CulinaryHistory = "Bucătăria maramureșeană tradițională poate fi considerată o bucătărie rustică pastorală, relativ simplă, care folosește un număr mic de ingrediente de bază (lapte de oaie, caș, urdă, jintiță, mălai, carne de porc sau de oaie, jumări, ouă, cartofi, varză, miere și prune) și care impresionează mai ales prin calitatea produselor finale.\r\nUn rol foarte important în bucătăria locală îl au prunele, folosite proaspete în rețete precum cea de gomboți cu prune, dar mai adesea conservate prin fierbere sau uscare. Din acestea se face horinca, versiunea locală a pălincii, băutură alcoolică dublu distilată, cu o tărie de 50–55%, uneori îndulcită cu miere de albine. Conserva consacrată de prune este magiunul, consumată cu mămăligă sau inclusă în prăjituri precum cornulețele, găluștele de aur sau porloșele. La fel ca în restul Ardealului, prunele uscate se folosesc în supe dulci sau sărate, sosuri pentru fripturi, tocănițe, mâncăruri de orez și în prăjituri.",
                            Name = "Maramures"
                        });
                });

            modelBuilder.Entity("CulinaryMap.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("CulinaryMap.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CulinaryMap.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CulinaryMap.Entities.Recipe", b =>
                {
                    b.HasOne("CulinaryMap.Entities.Region", "Region")
                        .WithMany("Recipes")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("CulinaryMap.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("CulinaryMap.Entities.IngredientDetails", "Ingredient")
                        .WithOne("RecipeIngredient")
                        .HasForeignKey("CulinaryMap.Entities.RecipeIngredient", "IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinaryMap.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CulinaryMap.Entities.UserRole", b =>
                {
                    b.HasOne("CulinaryMap.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinaryMap.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("CulinaryMap.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CulinaryMap.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CulinaryMap.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CulinaryMap.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CulinaryMap.Entities.IngredientDetails", b =>
                {
                    b.Navigation("RecipeIngredient")
                        .IsRequired();
                });

            modelBuilder.Entity("CulinaryMap.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("CulinaryMap.Entities.Region", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
